import { generateObject } from "ai";
import { type NextRequest, NextResponse } from "next/server";
import { modelIdForTask } from "@/lib/task-model";
import { resolveLanguageModel } from "@/lib/ai-provider";
import { getProviderReport } from "@/lib/provider-catalog";
import { z } from "zod";
import { apiError, missingField, withApiErrors } from "@/lib/api-error";
import { guardAiRoute, recordRouteUsage } from "@/lib/ai-route-guard";

// POST /api/agents/optimize
// Takes a free-text description and returns a structured agent config
// generated by AI. Never writes — returns JSON for the user to review.


const agentConfigSchema = z.object({
  name: z.string().describe("Short, descriptive name for the agent (2-4 words)"),
  description: z.string().describe("One-line summary of what the agent does"),
  systemPrompt: z
    .string()
    .describe(
      "Structured system prompt with: role definition, behavioral rules, and tool usage guidance. Write in the same language as the user's description.",
    ),
  tools: z
    .array(z.string())
    .describe(
      "Relevant tool names the agent should have access to. Pick from: upsert_contact, http_request, transfer_human, send_media, generate_media, run_python, calendar, reminder, propose_automation, propose_automation_update, list_automations",
    ),
});

const AVAILABLE_TOOLS = [
  "upsert_contact",
  "http_request",
  "transfer_human",
  "send_media",
  "generate_media",
  "run_python",
  "calendar",
  "reminder",
  "propose_automation",
  "propose_automation_update",
  "list_automations",
];

export const POST = withApiErrors(async function POST(request: NextRequest) {
  const refused = await guardAiRoute(request, "agents-optimize");
  if (refused) return refused;

  let body: unknown;
  try {
    body = await request.json();
  } catch {
    return apiError("invalid_json");
  }
  if (!body || typeof body !== "object") {
    return apiError("invalid_body");
  }

  const input = body as { description?: string };
  const description = input.description?.trim();
  if (!description) {
    return missingField("description");
  }

  const health = await getProviderReport();
  if (health.status === "missing" || health.status === "invalid") {
    return apiError("no_credentials");
  }

  const system = [
    "You design AI agent configurations for a business messaging platform.",
    "The user will describe what they want the agent to do in plain language.",
    "Generate a complete, ready-to-use agent configuration.",
    "",
    "## Output rules",
    "",
    "- name: short, descriptive, 2-4 words max.",
    "- description: one clear sentence.",
    "- systemPrompt: structured with sections:",
    "  1. **Role** — who the agent is and what it does.",
    "  2. **Rules** — behavioral guidelines (tone, language matching, brevity).",
    "  3. **Tools** — which tools to use and when, with brief explanations.",
    "- tools: pick ONLY from the available tools list. Include only tools the",
    "  agent genuinely needs. Always include transfer_human.",
    "",
    "## Available tools",
    "",
    ...AVAILABLE_TOOLS.map((t) => `- ${t}`),
    "",
    "## Constraints",
    "",
    "- Write the systemPrompt in the same language as the user's description.",
    "- Never fabricate tools not in the available list.",
    "- The systemPrompt must be practical and actionable, not generic fluff.",
    "- Keep the systemPrompt under 500 words.",
  ].join("\n");

  try {
    const modelId = await modelIdForTask("agent_design");
    const result = await generateObject({
      model: resolveLanguageModel(modelId),
      schema: agentConfigSchema,
      system,
      prompt: `User wants an agent that: ${description}`,
      abortSignal: AbortSignal.timeout(60_000),
    });
    await recordRouteUsage({ model: modelId, usage: result.usage, conversationId: "agents-optimize" });
    return NextResponse.json({ config: result.object });
  } catch (error) {
    return apiError("generation_failed", {
      detail: error instanceof Error ? error.message : String(error),
    });
  }
});
